apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web01
  namespace: app01
spec:
  ingressClassName: nginx
  rules:
    - host: web01.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web01
                port:
                  number: 80
