services:
  redis:
    image: redis:7-alpine
    container_name: redis-feis-1-v01
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - data-feis-1-v01:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    labels:
      org.bstu.owner: "skevet-avramuk"
      org.bstu.student.slug: "feis-1-v01"

  app:
    build: .
    container_name: app-feis-1-v01
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - STU_ID=1
      - STU_GROUP=feis
      - STU_VARIANT=v01
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -q --spider http://localhost:8081/health || exit 1"]
      interval: 30s
      timeout: 3s
      start_period: 20s
      retries: 3

    labels:
      org.bstu.owner: "skevet-avramuk"
      org.bstu.student.slug: "feis-1-v01"

volumes:
  data-feis-1-v01:
