apiVersion: v1
kind: Service
metadata:
  name: web20
  namespace: app20
  labels:
    app: web20
    org.bstu.student.fullname: "Stelmashuk_Ivan_Aleksandrovich"
    org.bstu.student.id: "220025"
    org.bstu.group: "AS-63"
    org.bstu.variant: "20"
    org.bstu.course: "RSIOT"
    org.bstu.owner: "KulibinI"
    org.bstu.student.slug: "as-63-220025-v20"
spec:
  selector:
    app: web20
  ports:
    - port: 80
      targetPort: 8054
  type: ClusterIP