services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: myapp:multi-stage
    container_name: flask-app
    ports:
      - "8094:8094"
    environment:
      - DB_HOST=postgres
      - DB_NAME=mydb
      - DB_USER=appuser
      - DB_PASS=password
    volumes:
      - app_data:/app/data
    user: "10001"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "-O-", "http://localhost:8094/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      postgres:
        condition: service_healthy
    stop_grace_period: 30s
    labels:
      - "org.bstu.owner=JonF1re"
      - "org.bstu.student.slug=as-64-220041-v8"

  postgres:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  app_data:
  postgres_data: