apiVersion: v1
kind: Secret
metadata:
  name: web21-secret
  namespace: app21
  labels:
    org.bstu.student.fullname: "Tunchik Anton Dmitrievich"
    org.bstu.student.id: "220026"
    org.bstu.group: "AS-63"
    org.bstu.variant: "21"
    org.bstu.course: "RSIOT"
    org.bstu.owner: "Stis25"
type: Opaque
stringData:
  STU_ID: "220026"
  GITHUB_USERNAME: "Stis25"
  STUDENT_FULLNAME: "Tunchik Anton Dmitrievich"