apiVersion: v1
kind: Service
metadata:
  name: net-as64-220044-v35
  namespace: app35
  labels:
    app: web35
    org.bstu.owner: Kirill-Kotkovets
    org.bstu.student.slug: as64-220044-v35
spec:
  type: NodePort
  selector:
    app: web35
  ports:
    - port: 8013
      targetPort: 8013
      nodePort: 30035
