apiVersion: v1
kind: ConfigMap
metadata:
  name: web16-config
  namespace: app16
  labels:
    app: web16
    org.bstu.student.slug: "as-63-220020-v16"
data:
  PORT: "8064"
  NODE_ENV: "production"
  LOG_LEVEL: "info"