apiVersion: v1
kind: Secret
metadata:
  name: web16-secret
  namespace: app16
  labels:
    app: web16
    org.bstu.student.slug: "as-63-220020-v16"
type: Opaque
stringData:
  DATABASE_URL: "postgres://app:app@postgres-service:5432/app_220020_v16"