apiVersion: v1
kind: ConfigMap
metadata:
  name: web18-config
  namespace: app18
  labels:
    org.bstu.student.fullname: Savko-Pavel-Stanislavovich
    org.bstu.student.id: "220023"
    org.bstu.group: AC-63
    org.bstu.variant: "18"
    org.bstu.course: RSIOT
    org.bstu.owner: 1nsirius
    org.bstu.student.slug: AC-63-220023-v18
    slug: AC-63--v18
data:
  PORT: "8052"
  HOST: "0.0.0.0"
  LOG_LEVEL: "info"
  STU_ID: "220023"
  STU_GROUP: "AC-63"
  STU_VARIANT: "18"
  PGSSLMODE: "disable"