apiVersion: v1
kind: Secret
metadata:
  name: web18-secret
  namespace: app18
  labels:
    org.bstu.student.fullname: Savko-Pavel-Stanislavovich
    org.bstu.student.id: "220023"
    org.bstu.group: AC-63
    org.bstu.variant: "18"
    org.bstu.course: RSIOT
    org.bstu.owner: 1nsirius
    org.bstu.student.slug: AC-63-220023-v18
    slug: AC-63--v18
type: Opaque
stringData:
  PGHOST: "localhost"
  PGPORT: "5432"
  PGUSER: "stuuser"
  PGPASSWORD: "stupass"
  PGDATABASE: "app_220023_v18"