apiVersion: v1
kind: Service
metadata:
  name: web18-service
  namespace: app18
  labels:
    app: web18
    org.bstu.student.fullname: Savko-Pavel-Stanislavovich
    org.bstu.student.id: "220023"
    org.bstu.group: AC-63
    org.bstu.variant: "18"
    org.bstu.course: RSIOT
    org.bstu.owner: 1nsirius
    org.bstu.student.slug: AC-63-220023-v18
    slug: AC-63--v18
spec:
  selector:
    app: web18
  ports:
  - port: 8052
    targetPort: 8052
    protocol: TCP
    name: http
  type: ClusterIP