apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web24
  namespace: app24
spec:
  ingressClassName: nginx
  rules:
    - host: web24.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web24
                port:
                  number: 80
