apiVersion: v1
kind: Service
metadata:
  name: web24
  namespace: app24
spec:
  selector:
    app: web24
  ports:
    - name: http
      protocol: TCP
      port: 80 # порт для доступа через Ingress
      targetPort: 8044 # порт контейнера web24
  type: ClusterIP
