apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app11
  labels:
    org.bstu.student.slug: "as-63-220015-v11"
data:
  APP_PORT: "8073"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"