apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app11
  labels:
    org.bstu.student.fullname: "Kulikovich-Ivan-Sergeevich"
    org.bstu.student.id: "220015"
    org.bstu.group: "AS-63"
    org.bstu.variant: "11"
    org.bstu.course: "RSIOT"
spec:
  type: ClusterIP
  selector:
    app: web11
  ports:
  - port: 8073
    targetPort: 8073
