apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: net-ingress-as63-220018-v14
  namespace: app14
  labels:
    app: web14
    org.bstu.owner: gleb7499
    org.bstu.student.slug: as63-220018-v14
    org.bstu.course: RSIOT
    org.bstu.student.id: "220018"
    org.bstu.group: "АС-63"
    org.bstu.variant: "14"
    org.bstu.student.fullname: "Логинов Глеб Олегович"
  annotations:
    org.bstu.student.fullname: "Логинов Глеб Олегович"
    org.bstu.description: "Ingress for Flask HTTP service (variant 14)"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: web14.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: net-as63-220018-v14
                port:
                  number: 80
