apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app14

labels:
  - pairs:
      org.bstu.owner: gleb7499
      org.bstu.student.slug: as63-220018-v14
      org.bstu.course: RSIOT
      org.bstu.student.id: "220018"
      org.bstu.group: "АС-63"
      org.bstu.variant: "14"

commonAnnotations:
  org.bstu.student.fullname: "Логинов Глеб Олегович"

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - db-deployment.yaml
  - db-service.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
