# ВНИМАНИЕ: Для production используйте сильные пароли!
# NOTE: For production use strong passwords!
# Эти учетные данные используются только для лабораторной работы
apiVersion: v1
kind: Secret
metadata:
  name: data-secret-as63-220018-v14
  namespace: app14
  labels:
    app: web14
    org.bstu.owner: gleb7499
    org.bstu.student.slug: as63-220018-v14
    org.bstu.course: RSIOT
    org.bstu.student.id: "220018"
    org.bstu.group: "АС-63"
    org.bstu.variant: "14"
    org.bstu.student.fullname: "Логинов Глеб Олегович"
type: Opaque
stringData:
  # Для production: используйте kubectl create secret generic с --from-literal
  # или внешние системы управления секретами (Vault, Sealed Secrets)
  DATABASE_URL: "postgresql://app_user:app_pass@data-db-as63-220018-v14:5432/app_220018_v14"
  POSTGRES_USER: "app_user"
  POSTGRES_PASSWORD: "app_pass"
  POSTGRES_DB: "app_220018_v14"
