apiVersion: v1
kind: ConfigMap
metadata:
  name: web17-config
  namespace: app17
  labels:
    org.bstu.student.fullname: "Vladislav_Vladimirovich_Poplavsky"
    org.bstu.student.id: "220021"
    org.bstu.group: "ASOI_63"
    org.bstu.variant: "17"
    org.bstu.course: "RSIOT"
    org.bstu.owner: "ImRaDeR1"
    org.bstu.student.slug: "asoi-63-220021-v17"
data:
  STU_ID: "220021"
  STU_GROUP: "ASOI 63"
  STU_VARIANT: "17"
  PORT: "8051"
  FLASK_ENV: "production"
  LOG_LEVEL: "INFO"
