apiVersion: v1
kind: Secret
metadata:
  name: web17-secret
  namespace: app17
  labels:
    org.bstu.student.fullname: "Vladislav_Vladimirovich_Poplavsky"
    org.bstu.student.id: "220021"
    org.bstu.group: "ASOI_63"
    org.bstu.variant: "17"
    org.bstu.course: "RSIOT"
    org.bstu.owner: "ImRaDeR1"
    org.bstu.student.slug: "asoi-63-220021-v17"
type: Opaque
stringData:
  REDIS_HOST: "web17-redis"  # ← ИЗМЕНИТЕ с localhost на web17-redis
  REDIS_PORT: "6379"
